<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
    The very first layer of the Neural Network. This layer takes in the data that the model will be trained on and it has one node for each of the features of the data.
### Hidden Layer:
    These are the layers in between the input and output layers. In these layers is where the NN applies weights and biases to the input to convert to output
### Output Layer:
    The output layer is the final layer of the NN. This is where the NN produces its result/prediction.
### Neuron:
    A neuron is a node in the neural network. Like in the brain, each neuron has an activation threshhold. So when data gets passed to it and the 
    weights and biases are calculated, it passes on the information if it surpasses that threshold.
    (This is not strictly true as it depends on the activation function. Some activation functions will pass on a corresponding weghted version of the feature,
    some will either pass it on or not in a binary way, and some will combine the two.)
### Weight:
    A weight is a number that the input data gets multiplied by. This adjusts the value corresponding to its impact on the final output.
### Activation Function:
    This determines the threshold of where the neuron in the network fires.
### Node Map:
    A visual representation of a neural network that shows things like how many layers there are and how many nodes there are per layer
### Perceptron:
    A very simple neural network with just 1 hidden layer with 1 node.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### The network starts with information being input at the first, input, layer. It then passes to the first hidden layer. Each node in the hidden layer will multiply all the features by the given weights and add them together along with bias constant. Then the activation function will determine if the node 'fires' to the next layer or not. This process reepeats for each layer of the network, until it reaches the output. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [13]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [14]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [15]:
inputs = np.array(df[['x1', 'x2']])
correct_outputs = np.array(df['y']).reshape(-1,1)

inputs, correct_outputs

(array([[0, 0],
        [1, 0],
        [0, 1],
        [1, 1]]), array([[1],
        [1],
        [1],
        [0]]))

In [16]:
weights = 2 * np.random.random((2,1)) -1
weights

array([[-0.22481678],
       [ 0.42217814]])

In [17]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[ 0.        ],
       [-0.22481678],
       [ 0.42217814],
       [ 0.19736136]])

In [18]:
activated_output = sigmoid(weighted_sum)

activated_output, correct_outputs

(array([[0.5       ],
        [0.44403134],
        [0.60400434],
        [0.54918081]]), array([[1],
        [1],
        [1],
        [0]]))

In [19]:
error = correct_outputs - activated_output

error

array([[ 0.5       ],
       [ 0.55596866],
       [ 0.39599566],
       [-0.54918081]])

In [20]:
adjustments = error * sigmoid_derivative(activated_output)

adjustments

array([[ 0.11750186],
       [ 0.13236011],
       [ 0.09049161],
       [-0.12744213]])

In [21]:
weights += np.dot(inputs.T, adjustments)

weights

array([[-0.2198988 ],
       [ 0.38522763]])

In [30]:
weights = 2 * np.random.random((2,1)) -1
for i in range(10000):
    
    weighted_sum = np.dot(inputs, weights)
    #print(weighted_sum)
    activated_output = sigmoid(weighted_sum)
    #print(activated_output)
    error = correct_outputs - activated_output
    #print(error)
    adjustments = error * sigmoid_derivative(activated_output)
    #print(adjustments)
    weights += np.dot(inputs.T, adjustments)
    if i % 100 == 0:
        print(weights)
print('Weights after training')
print(weights)

print("Output after training")
print(activated_output)

[[ 0.92272715]
 [-0.82742656]]
[[ 0.00099449]
 [-0.00099439]]
[[ 1.08342124e-06]
 [-1.08342112e-06]]
[[ 1.18036876e-09]
 [-1.18036887e-09]]
[[ 1.28594357e-12]
 [-1.28606847e-12]]
[[ 1.38777878e-15]
 [-1.34614542e-15]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[ 1.66533454e-16]
 [-3.19189120e-16]]
[[

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [1]:
import pandas as pd
import numpy as np

diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [2]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]
y = diabetes['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        weights = np.random.random((X.shape[1], 1))
        
        for i in range(self.niter):
            
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = (np.array(y).reshape(-1,1)) - activated_output
            # Update the Weights
            adjustments = error * self._Perceptron__sigmoid_derivative(activated_output)
            weights += np.dot(inputs.T, adjustments)
        return self

    def predict(self, X):
        """Return class label after unit step"""
        return None

In [13]:
p = Perceptron()

In [14]:
p.fit(X, y)

NameError: name 'sigmoid' is not defined

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?