<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
    A neuron is node in a layer of a neural network. The neurons calculate the weighted sum and use the activation function for determining what to pass on to next layer (depending on the function)
- **Input Layer:**
    This is the first layer of this Neural Net. It has one node/neuron for each feature
- **Hidden Layer:**
    These are all the layers in between the input and output layers. With each layer the input data gets a weighted sum calculated and is then acted upon by the activation function
- **Output Layer:**
    This is the final layer of the neural net. This will have as many nodes as outputs you want from the model. For a typical regression or binary classification this will typically be 1 node - just the single prediction. For multiclass-classification, such as in MNIST with img-number recognition, you would have an output node corresponding to all the possible outputs
- **Activation:**
    This is a function which determines what to pass on to the next layer. Most commonly, it is determining the strength, or weight, of the connection to the next layer.
- **Backpropagation:**
    

## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
import numpy as np

from scipy.special import expit
from sklearn.metrics import accuracy_score

candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
print(candy.shape)

candy.head()

(10000, 3)


chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. Explain why you could not achieve a higher accuracy with a *simple perceptron*. It's possible to achieve ~95% accuracy on this dataset.

In [3]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values.reshape(-1,1)

In [4]:
X.shape, y.shape

((10000, 2), (10000, 1))

In [5]:
# build Perceptron class
class Perceptron(object):
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # weights
        self.weight = np.random.rand(1 + X.shape[1])

        # Number of misclassifications
        self.errors = []  # Number of misclassifications

        for i in range(self.niter):
            err = 0
            for xi, target in zip(X, y):
                #print('weights:', self.weight)
                delta_w = self.rate * (target - self.predict(xi))
                #print('delta_w:', delta_w)
                self.weight[1:] += delta_w * xi
                self.weight[0] += delta_w
                #print(self.weight[0])
                err += int(delta_w != 0.0)
                self.errors.append(err)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, 0)

In [6]:
# for some reason i cant figure out the model doesnt learn
pn = Perceptron()
pn.fit(X,y)
preds = pn.predict(X)

In [10]:
print("True Output")
print(y)
print('-'*25)
print('Predicted Output')
print(preds)
print("Accuracy:", accuracy_score(y, preds))

True Output
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
-------------------------
Predicted Output
[1 1 1 ... 1 1 1]
Accuracy: 0.5


The reason the accuracy is limited with Perceptron is that it only finds linear relationships

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [12]:
# Multi-Layer Perceptron
class NeuralNetwork: 
    def __init__(self, n_iter=10, lr=0.1):
        # Set upArchietecture 
        self.inputs = 2
        self.hiddenNodes = 6
        self.outputNodes = 1
        self.n_iter = n_iter
        self.lr = lr
        
        #Initial weights
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes) #2x3
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #3x1
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Acivations of weighted sum
        self.activated_hidden = expit(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Final activation of output
        self.activated_output = expit(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = self.lr * (y - o) #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        for i in range(self.n_iter):
            o = self.feed_forward(X)
            self.backward(X, y, o)
        
    def accuracy(self, y):
        pred = np.array([1 if p>=0.5 else 0 for p in self.activated_output])
        y = y.reshape(1,-1)[0]
        return accuracy_score(y, pred)

In [13]:
X.shape, y.shape

((10000, 2), (10000, 1))

In [14]:
nn = NeuralNetwork()
nn.train(X,y)

In [15]:
# dont know why this model doesnt train
# same results everytime

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 100 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
        print("Accuracy:", nn.accuracy(y))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.94579606e-24]
 [1.11638588e-20]
 [1.94579606e-24]
 ...
 [1.94579606e-24]
 [1.94579606e-24]
 [1.11638588e-20]]
Loss: 
 0.49999999999999983
Accuracy: 0.5
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.94579606e-24]
 [1.11638588e-20]
 [1.94579606e-24]
 ...
 [1.94579606e-24]
 [1.94579606e-24]
 [1.11638588e-20]]
Loss: 
 0.49999999999999983
Accuracy: 0.5
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.94579606e-24]
 [1.11638588e-20]
 [1.94579606e-24]
 ...
 [1.94579606e-24]
 [1.94579606e-24]
 [1.11638588e-20]]
Loss: 
 0.49999999999999983
Accuracy: 0.5
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]


P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
102   63    0   1       140   195    0        1      179      0      0.0   
101   59    1   3       178   270    0        0      145      0      4.2   
242   64    1   0       145   212    0        0      132      0      2.0   
257   50    1   0       144   200    0        0      126      1      0.9   
225   70    1   0       145   174    0        1      125      1      2.6   

     slope  ca  thal  target  
102      2   2     2       1  
101      0   0     3       1  
242      1   2     1       0  
257      1   0     3       0  
225      0   0     3       0

In [16]:
# create x matrix and y vector
X = df.drop(columns='target').values
y = df['target'].values

In [17]:
# Majority Class Baseline
df['target'].value_counts(normalize=True)

1    0.544554
0    0.455446
Name: target, dtype: float64

Only 54.5%.

In [18]:
# scale X 
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [20]:
# create baseline model

model = Sequential()

model.add(Dense(13, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
# fit model with random chosen values for baseline
model.fit(X, y, batch_size=25, epochs=10, validation_split=0.1, verbose=True)

Train on 272 samples, validate on 31 samples
Epoch 1/10
272/272 [==============================] - 1s 4ms/sample - loss: 0.7739 - accuracy: 0.4706 - val_loss: 0.5200 - val_accuracy: 0.7419
Epoch 2/10
272/272 [==============================] - 0s 158us/sample - loss: 0.7227 - accuracy: 0.5110 - val_loss: 0.5033 - val_accuracy: 0.8065
Epoch 3/10
272/272 [==============================] - 0s 153us/sample - loss: 0.6776 - accuracy: 0.5699 - val_loss: 0.4867 - val_accuracy: 0.8387
Epoch 4/10
272/272 [==============================] - 0s 150us/sample - loss: 0.6437 - accuracy: 0.6213 - val_loss: 0.4721 - val_accuracy: 0.8387
Epoch 5/10
272/272 [==============================] - 0s 150us/sample - loss: 0.6164 - accuracy: 0.6765 - val_loss: 0.4611 - val_accuracy: 0.8710
Epoch 6/10
272/272 [==============================] - 0s 159us/sample - loss: 0.5932 - accuracy: 0.7243 - val_loss: 0.4492 - val_accuracy: 0.8387
Epoch 7/10
272/272 [==============================] - 0s 163us/sample - loss: 0.5

Well the baseline model does significantly better than the majority class.

Let's see about some Hyperparameter Tuning

In [22]:
# create model f(x) for keras sklearn wrapper
def create_model():
    model = Sequential()

    model.add(Dense(13, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dense(6, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

model = KerasClassifier(build_fn=create_model, verbose=True)

# exploring batch size
param_grid = {
    'batch_size': [10,20,30,40,50],
    'epochs': [10]
}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_results = grid.fit(X, y)

Train on 202 samples
Epoch 1/10


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


202/202 [==============================] - 0s 2ms/sample - loss: 0.6672 - accuracy: 0.5248
Epoch 2/10
202/202 [==============================] - 0s 270us/sample - loss: 0.6255 - accuracy: 0.6188
Epoch 3/10
202/202 [==============================] - 0s 269us/sample - loss: 0.5941 - accuracy: 0.7277
Epoch 4/10
202/202 [==============================] - 0s 270us/sample - loss: 0.5684 - accuracy: 0.7574
Epoch 5/10
202/202 [==============================] - 0s 271us/sample - loss: 0.5448 - accuracy: 0.7772
Epoch 6/10
202/202 [==============================] - 0s 272us/sample - loss: 0.5255 - accuracy: 0.7871
Epoch 7/10
202/202 [==============================] - 0s 276us/sample - loss: 0.5066 - accuracy: 0.8020
Epoch 8/10
202/202 [==============================] - 0s 295us/sample - loss: 0.4882 - accuracy: 0.8020
Epoch 9/10
202/202 [==============================] - 0s 266us/sample - loss: 0.4695 - accuracy: 0.8168
Epoch 10/10
202/202 [==============================] - 0s 312us/sample - loss

In [23]:
# Did only slightly better, but decided 10 was best batch size
print("Best Params:", grid_results.best_params_)
print("Best Score with these Params:", grid_results.best_score_)

Best Params: {'batch_size': 10, 'epochs': 10}
Best Score with these Params: 0.7986798683802286


In [24]:
# create model f(x) for keras sklearn wrapper
def create_model():
    model = Sequential()

    model.add(Dense(13, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dense(6, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

model = KerasClassifier(build_fn=create_model, verbose=True)

# now keep best batch size and explor epochs
param_grid = {
    'batch_size': [10],
    'epochs': [10, 20, 50, 100]
}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_results = grid.fit(X, y)

Train on 202 samples
Epoch 1/10
202/202 [==============================] - 1s 3ms/sample - loss: 0.6215 - accuracy: 0.6188
Epoch 2/10
202/202 [==============================] - 0s 261us/sample - loss: 0.5961 - accuracy: 0.6733
Epoch 3/10
202/202 [==============================] - 0s 270us/sample - loss: 0.5729 - accuracy: 0.7475
Epoch 4/10
202/202 [==============================] - 0s 264us/sample - loss: 0.5494 - accuracy: 0.7673
Epoch 5/10
202/202 [==============================] - 0s 286us/sample - loss: 0.5292 - accuracy: 0.7921
Epoch 6/10
202/202 [==============================] - 0s 255us/sample - loss: 0.5087 - accuracy: 0.8267
Epoch 7/10
202/202 [==============================] - 0s 255us/sample - loss: 0.4903 - accuracy: 0.8267
Epoch 8/10
202/202 [==============================] - 0s 257us/sample - loss: 0.4737 - accuracy: 0.8366
Epoch 9/10
202/202 [==============================] - 0s 266us/sample - loss: 0.4579 - accuracy: 0.8267
Epoch 10/10
202/202 [========================

In [25]:
# Epochs had a bigger impact than batch size - took it up to 81.5%
print("Best Params:", grid_results.best_params_)
print("Best Score with these Params:", grid_results.best_score_)

Best Params: {'batch_size': 10, 'epochs': 100}
Best Score with these Params: 0.8349834879239401
