<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import numpy as np

# Put data into arrays
X = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]
])

y = np.array([0,1,1,1,1,0,0]).reshape(-1,1)

In [2]:
# Creat NN class
class NeuralNetwork:
    def __init__(self, inputs=3, hiddenNodes=4):
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = 1
        
        np.random.seed(1112)
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes) * .01
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) * .01
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        self.hidden_sum = np.dot(X, self.weights1)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [3]:
# Instantiate NN
nn = NeuralNetwork()

In [4]:
X.shape, y.shape

((7, 3), (7, 1))

In [5]:
# loop over train 20000 times to train the model
for i in range(20000):
    if i <6 or i % 1000 == 0:
        print(f'Epoch {i}')
        print('-'*25)
        print('Inputs:', X)
        print('Ground Truth:', y)
        print('Predictions:', nn.feed_forward(X))
        print('-'*25)
    nn.train(X, y)

Epoch 0
-------------------------
Inputs: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Ground Truth: [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predictions: [[0.5025769 ]
 [0.50258076]
 [0.50258086]
 [0.50257383]
 [0.50257393]
 [0.50258472]
 [0.50256997]]
-------------------------
Epoch 1
-------------------------
Inputs: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Ground Truth: [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predictions: [[0.53283516]
 [0.5328917 ]
 [0.53289957]
 [0.53280976]
 [0.53281762]
 [0.53295611]
 [0.53275321]]
-------------------------
Epoch 2
-------------------------
Inputs: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Ground Truth: [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predictions: [[0.5496245 ]
 [0.54975019]
 [0.54976234]
 [0.54964028]
 [0.54965243]
 [0.54988801]
 [0.54951459]]
-------------------------
Epoch 3
-------------------------
Inputs: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Ground Truth

In [6]:
nn.train(X, y)

In [7]:
nn.feed_forward(X)

array([[0.00191176],
       [0.99189982],
       [0.99189975],
       [0.99210817],
       [0.99210817],
       [0.00631895],
       [0.01838535]])

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [8]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [9]:
# input image dimensions
img_rows, img_cols = 28, 28

In [10]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

np.count_nonzero(x_train), len(x_train)

(8994156, 60000)

In [11]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [12]:
# Now the data should be in a format you're more familiar with
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [13]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp.reshape(-1,1)

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp.reshape(-1,1)

In [14]:
# A Nice Binary target for ya to work with
np.count_nonzero(x_test)

1511219

### Estimating Your `net

In [15]:
nn2 = NeuralNetwork(inputs=784, hiddenNodes=512)

In [16]:
nn2.inputs, nn2.hiddenNodes

(784, 512)

In [17]:
X_sample = x_train[:25000, :]
y_sample = y_train.reshape(-1,1)[:25000]

In [18]:
y_sample

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [19]:
for i in range(100):
    nn2.train(x_train, y_train)
    
np.count_nonzero(nn2.activated_output)

0

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?